###
POST http://localhost:3000/workout HTTP/1.1
content-type: application/json

{
    "name": "Easy Run",
    "day": 1,
    "distance": 3.5,
    "duration": 35,
    "target": "Distance",
    "pace": "10:00"
}

###
POST http://localhost:3000/workout HTTP/1.1
content-type: application/json

{
    "name": "Tempo Run",
    "day": 2,
    "distance": 4,
    "duration": 36,
    "target": "Distance",
    "pace": "9:00"
}


###
GET http://localhost:3000/all_workouts HTTP/1.1